{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "self = <tests.functional.ui.pom_ui.test_contact_confirm.TestContactConfirm object at 0x7fc7c644bac0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c5fbeedd39cd5b7345edf9eec0abe97c\")>\n\n    @pytest.fixture()\n    def background(self, driver):\n        self.contact_confirm = ContactConfirm(driver)\n>       self.contact_confirm.load(driver)\n\nfunctional/ui/pom_ui/test_contact_confirm.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <lib.ui.page_objects.sample_ui.contact_confirm.ContactConfirm object at 0x7fc7c71a09a0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"c5fbeedd39cd5b7345edf9eec0abe97c\")>\n\n    def load(self, driver):\n>       self.driver = driver\nE       AttributeError: can't set attribute\n\n../lib/ui/page_objects/sample_ui/contact_confirm.py:17: AttributeError\n", "test_name": "test_contact_confirm", "rerun": "0"}}, "suite_name": "functional/ui/pom_ui/test_contact_confirm.py"}}}, "date": "June 02, 2022", "start_time": 1654176441.1643572, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}